name: Docker CI/CD - Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::680318115068:role/GitHubActions-ECR-Push-Role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories \
            --repository-names wildrydes-site \
            --region ap-south-1 || \
          aws ecr create-repository \
            --repository-name wildrydes-site \
            --region ap-south-1


      - name: Build Docker image
        run: |
          docker build -t wildrydes-site .

      - name: Tag Docker image
        run: |
          docker tag wildrydes-site:latest 680318115068.dkr.ecr.ap-south-1.amazonaws.com/wildrydes-site:latest

      - name: Push Docker image to ECR
        run: |
          docker push 680318115068.dkr.ecr.ap-south-1.amazonaws.com/wildrydes-site:latest

      - name: Register ECS Task Definition
        id: task-def
        run: |
          cat <<EOF > task-def.json
          {
            "family": "wildrydes-task",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "arn:aws:iam::680318115068:role/ecsTaskExecutionRole",
            "containerDefinitions": [
              {
                "name": "wildrydes-container",
                "image": "680318115068.dkr.ecr.ap-south-1.amazonaws.com/wildrydes-site:latest",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "protocol": "tcp"
                  }
                ]
              }
            ]
          }
          EOF

          aws ecs register-task-definition \
            --cli-input-json file://task-def.json \
            --region ap-south-1
    

      - name: Create ECS cluster if not exists
        run: |
          aws ecs describe-clusters \
            --clusters wildrydes-cluster \
            --region ap-south-1 \
            --query "clusters[?status=='ACTIVE'] | length(@)" \
            --output text | grep -q 1 || \
          aws ecs create-cluster \
            --cluster-name wildrydes-cluster \
            --region ap-south-1
    

      - name: Deploy to ECS (Force new deployment)
        run: |
          aws ecs update-service \
            --cluster wildrydes-cluster \
            --service wildrydes-service \
            --force-new-deployment \
            --region ap-south-1

